sudo: required
services:
  - docker

before_install:
  - docker build -t skaldat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skaldat/react-test npm run test -- --coverage

after_success:
  - docker build -t skaldat/multi-client ./client
  - docker build -t skaldat/multi-nginx ./nginx
  - docker build -t skaldat/multi-server ./server
  - docker build -t skaldat/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push skaldat/multi-client
  - docker push skaldat/multi-nginx
  - docker push skaldat/multi-server
  - docker push skaldat/multi-worker
  